spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/demo_crud
        username: postgres
        password: postgres
        driver-class-name: org.postgresql.Driver
    application:
        name: crud-one-to-many
